version: '3'
services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    command: npm run start
    volumes:
      - ./server:/app
      - ./app/node_modules
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - node
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - ./app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - node
  postgres:
    image: postgres:latest
    ports:
      - 5434:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    volumes:
      - data:/data/db2
    networks:
      - node

volumes:
  data:
    driver: local
networks:
  node:
    driver: bridge
